[package]
name = "my_first_azul_app"
version = "0.1.0"
authors = ["qholness"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colour = "0.5.0"
rodio = "0.11.0"